--
-- PostgreSQL database dump
--

\restrict kWmqMIrWBxaWEeJ2crYT3w07qSq2uLsDhEz6JRYd87778TaZMECrWLjpqacGfZi

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: user_info; Type: TABLE; Schema: public; Owner: web_user
--

CREATE TABLE public.user_info (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    failed_login_attempts integer NOT NULL,
    father_name character varying(100),
    is_active boolean NOT NULL,
    is_locked boolean NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    reset_token character varying(255),
    reset_token_expiry timestamp(6) without time zone,
    role character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(50) NOT NULL,
    CONSTRAINT user_info_role_check CHECK (((role)::text = ANY (ARRAY[('USER'::character varying)::text, ('ADMIN'::character varying)::text])))
);


ALTER TABLE public.user_info OWNER TO web_user;

--
-- Name: user_info_id_seq; Type: SEQUENCE; Schema: public; Owner: web_user
--

ALTER TABLE public.user_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: web_user
--

CREATE TABLE public.users (
    iduser integer NOT NULL,
    user_name character varying(100) NOT NULL,
    pass character varying(255) NOT NULL,
    email character varying(150) NOT NULL,
    fname character varying(100) NOT NULL
);


ALTER TABLE public.users OWNER TO web_user;

--
-- Name: users_iduser_seq; Type: SEQUENCE; Schema: public; Owner: web_user
--

CREATE SEQUENCE public.users_iduser_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_iduser_seq OWNER TO web_user;

--
-- Name: users_iduser_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: web_user
--

ALTER SEQUENCE public.users_iduser_seq OWNED BY public.users.iduser;


--
-- Name: users iduser; Type: DEFAULT; Schema: public; Owner: web_user
--

ALTER TABLE ONLY public.users ALTER COLUMN iduser SET DEFAULT nextval('public.users_iduser_seq'::regclass);


--
-- Data for Name: user_info; Type: TABLE DATA; Schema: public; Owner: web_user
--

COPY public.user_info (id, created_at, email, failed_login_attempts, father_name, is_active, is_locked, name, password, reset_token, reset_token_expiry, role, updated_at, username) FROM stdin;
1	2025-12-18 03:25:49.174556	test@example.com	0	Test Father	t	f	Test User	$2a$12$u2yl9gK6CBsjt4rqaiEN7ObWGJ3VTBsEBS93m/qFC.iWrOVL/GpIu	\N	\N	USER	2025-12-18 03:25:49.174598	testuser
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: web_user
--

COPY public.users (iduser, user_name, pass, email, fname) FROM stdin;
1	ubaid	ubaid123	ubaid@don.bigdon	Ubaid
2	ali	ali123	Ali@gmail.haider	Ali
3	love	love123	love@lovely.cute	Love
4	muskan	muskan123	muskan@gmail.com	muskan
\.


--
-- Name: user_info_id_seq; Type: SEQUENCE SET; Schema: public; Owner: web_user
--

SELECT pg_catalog.setval('public.user_info_id_seq', 1, true);


--
-- Name: users_iduser_seq; Type: SEQUENCE SET; Schema: public; Owner: web_user
--

SELECT pg_catalog.setval('public.users_iduser_seq', 4, true);


--
-- Name: user_info idx_email; Type: CONSTRAINT; Schema: public; Owner: web_user
--

ALTER TABLE ONLY public.user_info
    ADD CONSTRAINT idx_email UNIQUE (email);


--
-- Name: user_info idx_username; Type: CONSTRAINT; Schema: public; Owner: web_user
--

ALTER TABLE ONLY public.user_info
    ADD CONSTRAINT idx_username UNIQUE (username);


--
-- Name: user_info user_info_pkey; Type: CONSTRAINT; Schema: public; Owner: web_user
--

ALTER TABLE ONLY public.user_info
    ADD CONSTRAINT user_info_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: web_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: web_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (iduser);


--
-- Name: idx_reset_token; Type: INDEX; Schema: public; Owner: web_user
--

CREATE INDEX idx_reset_token ON public.user_info USING btree (reset_token);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO web_user;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO web_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO web_user;


--
-- PostgreSQL database dump complete
--

\unrestrict kWmqMIrWBxaWEeJ2crYT3w07qSq2uLsDhEz6JRYd87778TaZMECrWLjpqacGfZi

